fixes:
  - "moodle/mod/digitala/::"

ignore:
  - "classes/event/*"
  - "answerrecording_form.php"
  - "grade.php"
  - "index.php"
  - "lib.php"
  - "mod_form.php"
  - "renderer.php"
  - "renderable.php"
  - "view.php"
