version: '3.8'

services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /api
        image: digitala-test-api
        container_name: digitala-test-api
        volumes:
            - node_modules:/api/node_modules/
        ports:
          - 3000:3000

volumes:
    node_modules: