version: '3.8'

services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /api
        image: digitala-api
        container_name: digitala-api
        volumes:
            - node_modules:/api/node_modules/
        network_mode: "host"

volumes:
    node_modules: