name: Moodle Plugin CI for Moodle 3.9 and 3.11

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        php: ['7.3', '7.4']
        moodle-branch: ['MOODLE_39_STABLE']
        database: [pgsql]
        experimental: [false]
        coverage-location: ['./coverage.xml']
        coverage-engine: ['none']
        include:
          - php: '8.0'
            moodle-branch: 'MOODLE_311_STABLE'
            database: pgsql
            experimental: false
            coverage-location: './coverage/coverage.xml'
            coverage-engine: 'pcov'
          - php: '8.0'
            moodle-branch: 'master'
            database: pgsql
            experimental: true
            coverage-location: './coverage/coverage.xml'
            coverage-engine: 'pcov'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Edit API Docker-compose to use same network as Postgres
        run: |
          export network=$(docker network ls -f name=github --format "{{.Name}}")
          sed -i "s+REPLACE_THIS+${network}+g" ./plugin/scripts/local-api/docker-compose.yml
          cat ./plugin/scripts/local-api/docker-compose.yml

      - name: Setup API-container for testing
        run: docker-compose -f ./plugin/scripts/local-api/docker-compose.yml up -d

      - name: Print out API-containers logs
        run: echo $(docker logs digitala-api)

      - name: Test API is reachable
        run: |
          export ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' digitala-api)
          echo ${ip}
          curl http://${ip}:3000/

      - name: Add digitala-api to /etc/hosts
        run: |
          export ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' digitala-api)
          echo ${ip}
          sudo echo "${ip} digitala-api" | sudo tee -a /etc/hosts

      - name: Test API is reachable via hostname digitala-api
        run: |
          curl http://digitala-api:3000/

      - name: Print out API-containers logs
        run: echo $(docker logs digitala-api)

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}, pcov
          ini-values: max_input_vars=5000, memory_limit=-1, zend_enable_gc=0, max_file_size=100G, post_max_size=100G, upload_max_filesize=100G, tideways.log_segfaults=1
          coverage: ${{ matrix.coverage-engine }}

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: Checkout Moodle Browser Configs base
        uses: actions/checkout@v2
        with:
          repository: andrewnicols/moodle-browser-config
          path: moodle-browser-config

      - name: Add additional Behat Browsers
        run: |
          sed -i "s+// Extra config.+require_once('$(pwd)/moodle-browser-config/init.php');+g" moodle/config.php
          cp $(pwd)/plugin/tests/configs/localprofiles-ci $(pwd)/moodle-browser-config/localprofiles.php

      - name: PHP Lint
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci phplint

      - name: PHP Copy/Paste Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci codechecker --max-warnings 0

      - name: Moodle PHPDoc Checker
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci phpdoc

      - name: Validating
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        if: ${{ matrix.moodle-branch != 'master' }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: PHPUnit tests 7 # Something wrong with making coverage with PHP 8.0 and Moodle 3.11, so skipping it
        continue-on-error: ${{ matrix.experimental }}
        if: ${{ matrix.php != '8.0' }}
        run: moodle-plugin-ci phpunit --coverage-clover

      - name: PHPUnit tests 8.0 # Something wrong with making coverage with PHP 8.0 and Moodle 3.11, so skipping it
        continue-on-error: ${{ matrix.experimental }}
        if: ${{ matrix.php == '8.0' }}
        run: |
          mkdir coverage
          chmod 777 coverage
          cd moodle
          php admin/tool/phpunit/cli/init.php
          vendor/bin/phpunit --testsuite mod_digitala_testsuite --debug --coverage-clover $(pwd)/../coverage/coverage.xml
          cd ..

      - name: Codecov upload
        uses: codecov/codecov-action@v2
        if: ${{ always() }}
        with:
          files: ${{ matrix.coverage-location }}
          fail_ci_if_error: false
          root_dir: ./moodle/mod/digitala/
          name: ${{ matrix.moodle-branch }} (${{ matrix.php }})

      - name: Behat features
        continue-on-error: ${{ matrix.experimental }}
        if: ${{ always() }}
        run: |
          docker -v
          docker run -d --rm --name=selenium --net=host --shm-size=2g -v $(pwd)/moodle:$(pwd)/moodle selenium/standalone-chrome:3
          chmod +x ./plugin/scripts/phpserver.sh
          ./plugin/scripts/phpserver.sh
          cd $(pwd)/moodle
          php admin/tool/behat/cli/init.php
          php admin/tool/behat/cli/run.php --tags=@mod_digitala --profile=audiochrome --verbose -vvv --auto-rerun=2

  version:
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/zip-n-release' }}
    # needs: test

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Find PR
        uses: jwalton/gh-find-current-pr@v1
        id: pr
        with:
          state: all

      - name: Run bump-version.sh
        run: |
          chmod +x ./plugin/scripts/bump-version.sh
          ./plugin/scripts/bump-version.sh plugin

      - uses: EndBug/add-and-commit@v9
        id: version_commit
        with:
          add: version.php
          message: 'Bump version & release'
          cwd: './plugin'
          default_author: user_info

      - name: Echo info to files
        run: |
          mkdir info
          echo ${{ steps.pr.outputs }}
          echo ${{ steps.version_commit.outputs }}
          echo "title=${{ steps.pr.outputs.title }}" > info/pr-title
          echo "commit=${{ steps.version_commit.outputs.commit_sha }}" > info/version_commit
          echo $(cat info/pr-title)
          echo $(cat info/version_commit)

      - name: Upload info for zip-n-release
        uses: actions/upload-artifact@v3
        with:
          name: info
          path: |
            info/pr-title
            info/version_commit

  zip-n-release:
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/zip-n-release' }}
    needs: version

    steps:
      - name: Download info from version
        uses: actions/download-artifact@v3
        with:
          name: info
          path: info

      - name: Echo info to env
        run: |
          echo $(cat info/pr-title) >> $GITHUB_ENV
          echo $(cat info/version_commit) >> $GITHUB_ENV

      - name: Check if title and commit is okay
        run:
          |
          echo ${{env.title}}
          echo ${{env.commit}}

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{env.commmit}}
          path: digitala

      - name: Run zip.sh
        run: |
          chmod +x ./digitala/scripts/zip.sh
          ./digitala/scripts/zip.sh

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{env.release}}-${{env.version}}
          prerelease: false
          title: "${{env.release}} (${{env.version}}): ${{env.title}}"
          files: |
            moodle-mod-digitala-${{env.release_line}}-${{env.version}}.zip