name: Moodle Plugin CI for Moodle 3.9 and 3.11

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        php: ['7.3', '7.4']
        moodle-branch: ['MOODLE_39_STABLE']
        database: [pgsql]
        experimental: [false]
        include:
          - php: '8.0'
            moodle-branch: 'MOODLE_311_STABLE'
            database: pgsql
            experimental: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP Lint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: PHP Copy/Paste Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker --max-warnings 0

      - name: Moodle PHPDoc Checker
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc

      - name: Validating
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        if: ${{ false }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: PHPUnit tests # Something wrong with making coverage with PHP 8.0 and Moodle 3.11, so skipping it
        if: ${{ !matrix.experimental }}
        run: moodle-plugin-ci phpunit --coverage-clover

      - name: Behat features
        if: ${{ false }}
        run: moodle-plugin-ci behat --profile chrome

      - name: Codecov upload
        uses: codecov/codecov-action@v2
        if: ${{ !matrix.experimental }} # Skip in PHP 8.0 since tests are not run at the moment
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          name: ${{ matrix.moodle-branch }} (${{ matrix.php }})

  version:
    runs-on: ubuntu-18.04
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Run bump-version.sh
        run: |
          chmod +x ./plugin/scripts/bump-version.sh
          ./plugin/scripts/bump-version.sh

      - uses: EndBug/add-and-commit@v8
        with:
          add: version.php
          message: 'Bump version'
          cwd: './plugin'
          default_author: user_info
